//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_App.ServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="New_Project_Table", Namespace="http://schemas.datacontract.org/2004/07/wcf_itp_sa")]
    [System.SerializableAttribute()]
    public partial class New_Project_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Proj_DesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Proj_EdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Proj_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Proj_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Proj_SdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Proj_StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Name {
            get {
                return this.Emp_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_NameField, value) != true)) {
                    this.Emp_NameField = value;
                    this.RaisePropertyChanged("Emp_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proj_Des {
            get {
                return this.Proj_DesField;
            }
            set {
                if ((object.ReferenceEquals(this.Proj_DesField, value) != true)) {
                    this.Proj_DesField = value;
                    this.RaisePropertyChanged("Proj_Des");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Proj_Edate {
            get {
                return this.Proj_EdateField;
            }
            set {
                if ((this.Proj_EdateField.Equals(value) != true)) {
                    this.Proj_EdateField = value;
                    this.RaisePropertyChanged("Proj_Edate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proj_Id {
            get {
                return this.Proj_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Proj_IdField, value) != true)) {
                    this.Proj_IdField = value;
                    this.RaisePropertyChanged("Proj_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proj_Name {
            get {
                return this.Proj_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Proj_NameField, value) != true)) {
                    this.Proj_NameField = value;
                    this.RaisePropertyChanged("Proj_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Proj_Sdate {
            get {
                return this.Proj_SdateField;
            }
            set {
                if ((this.Proj_SdateField.Equals(value) != true)) {
                    this.Proj_SdateField = value;
                    this.RaisePropertyChanged("Proj_Sdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proj_Status {
            get {
                return this.Proj_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.Proj_StatusField, value) != true)) {
                    this.Proj_StatusField = value;
                    this.RaisePropertyChanged("Proj_Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee_Table", Namespace="http://schemas.datacontract.org/2004/07/wcf_itp_sa")]
    [System.SerializableAttribute()]
    public partial class Employee_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Id {
            get {
                return this.Emp_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_IdField, value) != true)) {
                    this.Emp_IdField = value;
                    this.RaisePropertyChanged("Emp_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Name {
            get {
                return this.Emp_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_NameField, value) != true)) {
                    this.Emp_NameField = value;
                    this.RaisePropertyChanged("Emp_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_All_Items", ReplyAction="http://tempuri.org/IService1/get_All_ItemsResponse")]
        OA_App.ServiceRef.New_Project_Table[] get_All_Items();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_UserType", ReplyAction="http://tempuri.org/IService1/Select_UserTypeResponse")]
        string Select_UserType(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_EmployeeDetails", ReplyAction="http://tempuri.org/IService1/get_EmployeeDetailsResponse")]
        OA_App.ServiceRef.Employee_Table[] get_EmployeeDetails();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : OA_App.ServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<OA_App.ServiceRef.IService1>, OA_App.ServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OA_App.ServiceRef.New_Project_Table[] get_All_Items() {
            return base.Channel.get_All_Items();
        }
        
        public string Select_UserType(string id) {
            return base.Channel.Select_UserType(id);
        }
        
        public OA_App.ServiceRef.Employee_Table[] get_EmployeeDetails() {
            return base.Channel.get_EmployeeDetails();
        }
    }
}
