<?xml version="1.0" encoding="utf-8"?><Database Name="OA_APP" Class="OADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Laptop;Initial Catalog=OA_APP;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OA_APPConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee_Table" Member="Employee_Tables">
    <Type Name="Employee_Table">
      <Column Name="Emp_Id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Emp_Name" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Project_Table_New" Member="Project_Table_News">
    <Type Name="Project_Table_New">
      <Column Name="Proj_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Proj_Name" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Proj_Des" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Proj_Sdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Proj_Edate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Proj_Status" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Emp_Name" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserLogin_Table" Member="UserLogin_Tables">
    <Type Name="UserLogin_Table">
      <Column Name="User_Id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="User_Type" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>