#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_itp_sa
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OA_APP")]
	public partial class OA_DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDocument(Document instance);
    partial void UpdateDocument(Document instance);
    partial void DeleteDocument(Document instance);
    partial void InsertEmployee_Table(Employee_Table instance);
    partial void UpdateEmployee_Table(Employee_Table instance);
    partial void DeleteEmployee_Table(Employee_Table instance);
    partial void InsertProject_Table_New(Project_Table_New instance);
    partial void UpdateProject_Table_New(Project_Table_New instance);
    partial void DeleteProject_Table_New(Project_Table_New instance);
    partial void InsertUserLogin_Table(UserLogin_Table instance);
    partial void UpdateUserLogin_Table(UserLogin_Table instance);
    partial void DeleteUserLogin_Table(UserLogin_Table instance);
    #endregion
		
		public OA_DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OA_APPConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OA_DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OA_DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OA_DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OA_DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Document> Documents
		{
			get
			{
				return this.GetTable<Document>();
			}
		}
		
		public System.Data.Linq.Table<Employee_Table> Employee_Tables
		{
			get
			{
				return this.GetTable<Employee_Table>();
			}
		}
		
		public System.Data.Linq.Table<Project_Table_New> Project_Table_News
		{
			get
			{
				return this.GetTable<Project_Table_New>();
			}
		}
		
		public System.Data.Linq.Table<UserLogin_Table> UserLogin_Tables
		{
			get
			{
				return this.GetTable<UserLogin_Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Document")]
	public partial class Document : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Proj_Id;
		
		private int _Doc_Id;
		
		private string _Doc_Name;
		
		private string _Status;
		
		private string _Path;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProj_IdChanging(int value);
    partial void OnProj_IdChanged();
    partial void OnDoc_IdChanging(int value);
    partial void OnDoc_IdChanged();
    partial void OnDoc_NameChanging(string value);
    partial void OnDoc_NameChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    #endregion
		
		public Document()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proj_Id", DbType="Int NOT NULL")]
		public int Proj_Id
		{
			get
			{
				return this._Proj_Id;
			}
			set
			{
				if ((this._Proj_Id != value))
				{
					this.OnProj_IdChanging(value);
					this.SendPropertyChanging();
					this._Proj_Id = value;
					this.SendPropertyChanged("Proj_Id");
					this.OnProj_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Doc_Id
		{
			get
			{
				return this._Doc_Id;
			}
			set
			{
				if ((this._Doc_Id != value))
				{
					this.OnDoc_IdChanging(value);
					this.SendPropertyChanging();
					this._Doc_Id = value;
					this.SendPropertyChanged("Doc_Id");
					this.OnDoc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Name", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Doc_Name
		{
			get
			{
				return this._Doc_Name;
			}
			set
			{
				if ((this._Doc_Name != value))
				{
					this.OnDoc_NameChanging(value);
					this.SendPropertyChanging();
					this._Doc_Name = value;
					this.SendPropertyChanged("Doc_Name");
					this.OnDoc_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this.OnPathChanging(value);
					this.SendPropertyChanging();
					this._Path = value;
					this.SendPropertyChanged("Path");
					this.OnPathChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee_Table")]
	public partial class Employee_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Emp_Id;
		
		private string _Emp_Name;
		
		private string _Contact;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmp_IdChanging(string value);
    partial void OnEmp_IdChanged();
    partial void OnEmp_NameChanging(string value);
    partial void OnEmp_NameChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Employee_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Emp_Id
		{
			get
			{
				return this._Emp_Id;
			}
			set
			{
				if ((this._Emp_Id != value))
				{
					this.OnEmp_IdChanging(value);
					this.SendPropertyChanging();
					this._Emp_Id = value;
					this.SendPropertyChanged("Emp_Id");
					this.OnEmp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Name", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Emp_Name
		{
			get
			{
				return this._Emp_Name;
			}
			set
			{
				if ((this._Emp_Name != value))
				{
					this.OnEmp_NameChanging(value);
					this.SendPropertyChanging();
					this._Emp_Name = value;
					this.SendPropertyChanged("Emp_Name");
					this.OnEmp_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(20)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Project_Table_New")]
	public partial class Project_Table_New : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Proj_Id;
		
		private string _Proj_Name;
		
		private string _Proj_Des;
		
		private System.DateTime _Proj_Sdate;
		
		private System.DateTime _Proj_Edate;
		
		private string _Proj_Status;
		
		private string _Emp_Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProj_IdChanging(int value);
    partial void OnProj_IdChanged();
    partial void OnProj_NameChanging(string value);
    partial void OnProj_NameChanged();
    partial void OnProj_DesChanging(string value);
    partial void OnProj_DesChanged();
    partial void OnProj_SdateChanging(System.DateTime value);
    partial void OnProj_SdateChanged();
    partial void OnProj_EdateChanging(System.DateTime value);
    partial void OnProj_EdateChanged();
    partial void OnProj_StatusChanging(string value);
    partial void OnProj_StatusChanged();
    partial void OnEmp_NameChanging(string value);
    partial void OnEmp_NameChanged();
    #endregion
		
		public Project_Table_New()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proj_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Proj_Id
		{
			get
			{
				return this._Proj_Id;
			}
			set
			{
				if ((this._Proj_Id != value))
				{
					this.OnProj_IdChanging(value);
					this.SendPropertyChanging();
					this._Proj_Id = value;
					this.SendPropertyChanged("Proj_Id");
					this.OnProj_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proj_Name", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Proj_Name
		{
			get
			{
				return this._Proj_Name;
			}
			set
			{
				if ((this._Proj_Name != value))
				{
					this.OnProj_NameChanging(value);
					this.SendPropertyChanging();
					this._Proj_Name = value;
					this.SendPropertyChanged("Proj_Name");
					this.OnProj_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proj_Des", DbType="VarChar(MAX)")]
		public string Proj_Des
		{
			get
			{
				return this._Proj_Des;
			}
			set
			{
				if ((this._Proj_Des != value))
				{
					this.OnProj_DesChanging(value);
					this.SendPropertyChanging();
					this._Proj_Des = value;
					this.SendPropertyChanged("Proj_Des");
					this.OnProj_DesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proj_Sdate", DbType="Date NOT NULL")]
		public System.DateTime Proj_Sdate
		{
			get
			{
				return this._Proj_Sdate;
			}
			set
			{
				if ((this._Proj_Sdate != value))
				{
					this.OnProj_SdateChanging(value);
					this.SendPropertyChanging();
					this._Proj_Sdate = value;
					this.SendPropertyChanged("Proj_Sdate");
					this.OnProj_SdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proj_Edate", DbType="Date NOT NULL")]
		public System.DateTime Proj_Edate
		{
			get
			{
				return this._Proj_Edate;
			}
			set
			{
				if ((this._Proj_Edate != value))
				{
					this.OnProj_EdateChanging(value);
					this.SendPropertyChanging();
					this._Proj_Edate = value;
					this.SendPropertyChanged("Proj_Edate");
					this.OnProj_EdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proj_Status", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Proj_Status
		{
			get
			{
				return this._Proj_Status;
			}
			set
			{
				if ((this._Proj_Status != value))
				{
					this.OnProj_StatusChanging(value);
					this.SendPropertyChanging();
					this._Proj_Status = value;
					this.SendPropertyChanged("Proj_Status");
					this.OnProj_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Name", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Emp_Name
		{
			get
			{
				return this._Emp_Name;
			}
			set
			{
				if ((this._Emp_Name != value))
				{
					this.OnEmp_NameChanging(value);
					this.SendPropertyChanging();
					this._Emp_Name = value;
					this.SendPropertyChanged("Emp_Name");
					this.OnEmp_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserLogin_Table")]
	public partial class UserLogin_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _User_Id;
		
		private string _Password;
		
		private string _User_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdChanging(string value);
    partial void OnUser_IdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUser_TypeChanging(string value);
    partial void OnUser_TypeChanged();
    #endregion
		
		public UserLogin_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Type", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string User_Type
		{
			get
			{
				return this._User_Type;
			}
			set
			{
				if ((this._User_Type != value))
				{
					this.OnUser_TypeChanging(value);
					this.SendPropertyChanging();
					this._User_Type = value;
					this.SendPropertyChanged("User_Type");
					this.OnUser_TypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
