#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_itp_sa
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ITP2016")]
	public partial class tempdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertItem_IT13020040_tb(Item_IT13020040_tb instance);
    partial void UpdateItem_IT13020040_tb(Item_IT13020040_tb instance);
    partial void DeleteItem_IT13020040_tb(Item_IT13020040_tb instance);
    #endregion
		
		public tempdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ITP2016ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public tempdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tempdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tempdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tempdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Item_IT13020040_tb> Item_IT13020040_tbs
		{
			get
			{
				return this.GetTable<Item_IT13020040_tb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_IT13020040_tb")]
	public partial class Item_IT13020040_tb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Item_Id;
		
		private string _Item_Name;
		
		private string _Item_Des;
		
		private System.Nullable<double> _Item_Price;
		
		private string _Item_Image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItem_IdChanging(int value);
    partial void OnItem_IdChanged();
    partial void OnItem_NameChanging(string value);
    partial void OnItem_NameChanged();
    partial void OnItem_DesChanging(string value);
    partial void OnItem_DesChanged();
    partial void OnItem_PriceChanging(System.Nullable<double> value);
    partial void OnItem_PriceChanged();
    partial void OnItem_ImageChanging(string value);
    partial void OnItem_ImageChanged();
    #endregion
		
		public Item_IT13020040_tb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Item_Id
		{
			get
			{
				return this._Item_Id;
			}
			set
			{
				if ((this._Item_Id != value))
				{
					this.OnItem_IdChanging(value);
					this.SendPropertyChanging();
					this._Item_Id = value;
					this.SendPropertyChanged("Item_Id");
					this.OnItem_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Name", DbType="VarChar(200)")]
		public string Item_Name
		{
			get
			{
				return this._Item_Name;
			}
			set
			{
				if ((this._Item_Name != value))
				{
					this.OnItem_NameChanging(value);
					this.SendPropertyChanging();
					this._Item_Name = value;
					this.SendPropertyChanged("Item_Name");
					this.OnItem_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Des", DbType="VarChar(MAX)")]
		public string Item_Des
		{
			get
			{
				return this._Item_Des;
			}
			set
			{
				if ((this._Item_Des != value))
				{
					this.OnItem_DesChanging(value);
					this.SendPropertyChanging();
					this._Item_Des = value;
					this.SendPropertyChanged("Item_Des");
					this.OnItem_DesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Price", DbType="Float")]
		public System.Nullable<double> Item_Price
		{
			get
			{
				return this._Item_Price;
			}
			set
			{
				if ((this._Item_Price != value))
				{
					this.OnItem_PriceChanging(value);
					this.SendPropertyChanging();
					this._Item_Price = value;
					this.SendPropertyChanged("Item_Price");
					this.OnItem_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Image", DbType="VarChar(MAX)")]
		public string Item_Image
		{
			get
			{
				return this._Item_Image;
			}
			set
			{
				if ((this._Item_Image != value))
				{
					this.OnItem_ImageChanging(value);
					this.SendPropertyChanging();
					this._Item_Image = value;
					this.SendPropertyChanged("Item_Image");
					this.OnItem_ImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
