//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_App.SRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project_Table", Namespace="http://schemas.datacontract.org/2004/07/wcf_itp_sa")]
    [System.SerializableAttribute()]
    public partial class Project_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Proj_DesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Proj_EdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Proj_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Proj_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Proj_SdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Proj_StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Name {
            get {
                return this.Emp_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_NameField, value) != true)) {
                    this.Emp_NameField = value;
                    this.RaisePropertyChanged("Emp_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proj_Des {
            get {
                return this.Proj_DesField;
            }
            set {
                if ((object.ReferenceEquals(this.Proj_DesField, value) != true)) {
                    this.Proj_DesField = value;
                    this.RaisePropertyChanged("Proj_Des");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Proj_Edate {
            get {
                return this.Proj_EdateField;
            }
            set {
                if ((this.Proj_EdateField.Equals(value) != true)) {
                    this.Proj_EdateField = value;
                    this.RaisePropertyChanged("Proj_Edate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Proj_Id {
            get {
                return this.Proj_IdField;
            }
            set {
                if ((this.Proj_IdField.Equals(value) != true)) {
                    this.Proj_IdField = value;
                    this.RaisePropertyChanged("Proj_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proj_Name {
            get {
                return this.Proj_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Proj_NameField, value) != true)) {
                    this.Proj_NameField = value;
                    this.RaisePropertyChanged("Proj_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Proj_Sdate {
            get {
                return this.Proj_SdateField;
            }
            set {
                if ((this.Proj_SdateField.Equals(value) != true)) {
                    this.Proj_SdateField = value;
                    this.RaisePropertyChanged("Proj_Sdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proj_Status {
            get {
                return this.Proj_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.Proj_StatusField, value) != true)) {
                    this.Proj_StatusField = value;
                    this.RaisePropertyChanged("Proj_Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee_Table", Namespace="http://schemas.datacontract.org/2004/07/wcf_itp_sa")]
    [System.SerializableAttribute()]
    public partial class Employee_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Id {
            get {
                return this.Emp_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_IdField, value) != true)) {
                    this.Emp_IdField = value;
                    this.RaisePropertyChanged("Emp_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Name {
            get {
                return this.Emp_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_NameField, value) != true)) {
                    this.Emp_NameField = value;
                    this.RaisePropertyChanged("Emp_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_ProjectsItems_By_Month", ReplyAction="http://tempuri.org/IService1/get_ProjectsItems_By_MonthResponse")]
        OA_App.SRef.Project_Table[] get_ProjectsItems_By_Month(int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_ProjectsItems_By_Status", ReplyAction="http://tempuri.org/IService1/get_ProjectsItems_By_StatusResponse")]
        OA_App.SRef.Project_Table[] get_ProjectsItems_By_Status(string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_All_ProjectsItems", ReplyAction="http://tempuri.org/IService1/get_All_ProjectsItemsResponse")]
        OA_App.SRef.Project_Table[] get_All_ProjectsItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_All_EmployeeDeatils", ReplyAction="http://tempuri.org/IService1/get_All_EmployeeDeatilsResponse")]
        OA_App.SRef.Employee_Table[] get_All_EmployeeDeatils();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_LogInDetails", ReplyAction="http://tempuri.org/IService1/Select_LogInDetailsResponse")]
        string Select_LogInDetails(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_All_EmpWindowItems", ReplyAction="http://tempuri.org/IService1/get_All_EmpWindowItemsResponse")]
        OA_App.SRef.Project_Table[] get_All_EmpWindowItems(string emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert_Project", ReplyAction="http://tempuri.org/IService1/Insert_ProjectResponse")]
        bool Insert_Project(int id, string name, string des, System.DateTime sdate, System.DateTime edate, string ename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update_Project", ReplyAction="http://tempuri.org/IService1/Update_ProjectResponse")]
        bool Update_Project(int id, string name, string des, System.DateTime sdate, System.DateTime edate, char stat, string ename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Project", ReplyAction="http://tempuri.org/IService1/Delete_ProjectResponse")]
        bool Delete_Project(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/search_Projects", ReplyAction="http://tempuri.org/IService1/search_ProjectsResponse")]
        OA_App.SRef.Project_Table[] search_Projects(string user_value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_next_Id", ReplyAction="http://tempuri.org/IService1/get_next_IdResponse")]
        int get_next_Id();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update_Employee_table", ReplyAction="http://tempuri.org/IService1/Update_Employee_tableResponse")]
        bool Update_Employee_table(string id, string name, string email, string contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update_Employee_UserLogin_Table", ReplyAction="http://tempuri.org/IService1/Update_Employee_UserLogin_TableResponse")]
        bool Update_Employee_UserLogin_Table(string UID, string PSW);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert_Employee", ReplyAction="http://tempuri.org/IService1/Insert_EmployeeResponse")]
        bool Insert_Employee(string id, string name, string email, string contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert_Employee_UserLogin_Table", ReplyAction="http://tempuri.org/IService1/Insert_Employee_UserLogin_TableResponse")]
        bool Insert_Employee_UserLogin_Table(string UID, string PSW);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Employee_form_Emp_table", ReplyAction="http://tempuri.org/IService1/Delete_Employee_form_Emp_tableResponse")]
        bool Delete_Employee_form_Emp_table(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Employee_form_User_Login_table", ReplyAction="http://tempuri.org/IService1/Delete_Employee_form_User_Login_tableResponse")]
        bool Delete_Employee_form_User_Login_table(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadDocument", ReplyAction="http://tempuri.org/IService1/DownloadDocumentResponse")]
        byte[] DownloadDocument(int projectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadFile", ReplyAction="http://tempuri.org/IService1/UploadFileResponse")]
        bool UploadFile(int projectId, string fileName, byte[] uplodingDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadCompleteDocument", ReplyAction="http://tempuri.org/IService1/DownloadCompleteDocumentResponse")]
        byte[] DownloadCompleteDocument(int projectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadAdminFile", ReplyAction="http://tempuri.org/IService1/UploadAdminFileResponse")]
        bool UploadAdminFile(int projectId, string fileName, byte[] uplodingDocument);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : OA_App.SRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<OA_App.SRef.IService1>, OA_App.SRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OA_App.SRef.Project_Table[] get_ProjectsItems_By_Month(int month) {
            return base.Channel.get_ProjectsItems_By_Month(month);
        }
        
        public OA_App.SRef.Project_Table[] get_ProjectsItems_By_Status(string Status) {
            return base.Channel.get_ProjectsItems_By_Status(Status);
        }
        
        public OA_App.SRef.Project_Table[] get_All_ProjectsItems() {
            return base.Channel.get_All_ProjectsItems();
        }
        
        public OA_App.SRef.Employee_Table[] get_All_EmployeeDeatils() {
            return base.Channel.get_All_EmployeeDeatils();
        }
        
        public string Select_LogInDetails(string id) {
            return base.Channel.Select_LogInDetails(id);
        }
        
        public OA_App.SRef.Project_Table[] get_All_EmpWindowItems(string emp) {
            return base.Channel.get_All_EmpWindowItems(emp);
        }
        
        public bool Insert_Project(int id, string name, string des, System.DateTime sdate, System.DateTime edate, string ename) {
            return base.Channel.Insert_Project(id, name, des, sdate, edate, ename);
        }
        
        public bool Update_Project(int id, string name, string des, System.DateTime sdate, System.DateTime edate, char stat, string ename) {
            return base.Channel.Update_Project(id, name, des, sdate, edate, stat, ename);
        }
        
        public bool Delete_Project(int id) {
            return base.Channel.Delete_Project(id);
        }
        
        public OA_App.SRef.Project_Table[] search_Projects(string user_value) {
            return base.Channel.search_Projects(user_value);
        }
        
        public int get_next_Id() {
            return base.Channel.get_next_Id();
        }
        
        public bool Update_Employee_table(string id, string name, string email, string contact) {
            return base.Channel.Update_Employee_table(id, name, email, contact);
        }
        
        public bool Update_Employee_UserLogin_Table(string UID, string PSW) {
            return base.Channel.Update_Employee_UserLogin_Table(UID, PSW);
        }
        
        public bool Insert_Employee(string id, string name, string email, string contact) {
            return base.Channel.Insert_Employee(id, name, email, contact);
        }
        
        public bool Insert_Employee_UserLogin_Table(string UID, string PSW) {
            return base.Channel.Insert_Employee_UserLogin_Table(UID, PSW);
        }
        
        public bool Delete_Employee_form_Emp_table(string id) {
            return base.Channel.Delete_Employee_form_Emp_table(id);
        }
        
        public bool Delete_Employee_form_User_Login_table(string id) {
            return base.Channel.Delete_Employee_form_User_Login_table(id);
        }
        
        public byte[] DownloadDocument(int projectID) {
            return base.Channel.DownloadDocument(projectID);
        }
        
        public bool UploadFile(int projectId, string fileName, byte[] uplodingDocument) {
            return base.Channel.UploadFile(projectId, fileName, uplodingDocument);
        }
        
        public byte[] DownloadCompleteDocument(int projectID) {
            return base.Channel.DownloadCompleteDocument(projectID);
        }
        
        public bool UploadAdminFile(int projectId, string fileName, byte[] uplodingDocument) {
            return base.Channel.UploadAdminFile(projectId, fileName, uplodingDocument);
        }
    }
}
